"""
This script finds the best hyperparameter combination using random Search

This script may takes several days to complete
If FAST_MODE = True, it will directly read the fitness of a chromosome from 'results/fitness_table' generated by Grid Search

"""

import numpy as np
import pandas as pd
from casper_test import rkf_validator
from utilities import import_data
from utilities import set_seed
from sklearn.model_selection import train_test_split
from hypers_grid_search import HYPERPARAMETERS_CANDIDATES
from hypers_grid_search import SEARCH_SPACE_SIZE
from hypers_grid_search import chromosome_to_hyperparameters

# Use the result from grid search when calculate the score of a chromosome
FAST_MODE = True

# Number of random hyperparameter combinations to test
N_SAMPLES = 200

DNA_SIZE = 12

DEVICE = 'cpu'

# set seed
SEED = None
if SEED is not None:
    set_seed(SEED)

# Number of training for each hyperparameter combination
N_SPLITS = 10
N_REPEATS = 4

# The scores for all 4096 possible chromosomes
FITNESS_TABLE = pd.read_csv('results/fitness_table.csv', index_col=0, dtype={0: str})


def random_search(train_data):
    """
    Randomly sample hyperparameters and evaluate them
    """
    best_score = float('inf')
    best_chromosome = None

    for i in range(N_SAMPLES):
        chromosome = ''.join(map(str, np.random.randint(2, size=DNA_SIZE)))
        if FAST_MODE:
            MSE = FITNESS_TABLE.loc[chromosome][0]
        else:
            hyperparameters = chromosome_to_hyperparameters(chromosome)
            MSE = rkf_validator(train_data, hyperparameters, N_SPLITS, N_REPEATS, device=DEVICE, fast_mode=True, verbose=False)
        if MSE < best_score:
            best_score = MSE
            best_chromosome = chromosome
        print(f'Sample: {i + 1}/{N_SAMPLES}   Hyperparameters: {chromosome_to_hyperparameters(chromosome)}   MSE: {MSE}')

    return best_chromosome, best_score

def main():
    # import data
    data, _, _ = import_data()
    train_data, test_data, _, _ = train_test_split(data, data.iloc[:, 0], test_size=0.2, random_state=SEED)
    best_chromosome, best_score = random_search(train_data)
    print(f"Best Hyperparameters: {chromosome_to_hyperparameters(best_chromosome)}   MSE: {best_score}")

if __name__ == "__main__":
    main()